display_name: ZAI-X
publisher_display_name: AliceRabbit
identity_name: io.github.alicerabbit.zaix
logo_path: assets/images/logo.png
capabilities: internetClient
languages: zh-cn
install_certificate: "false"