// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:zaix/models/db/comic_download_info.dart';
import 'package:zaix/models/db/comic_history.dart';
import 'package:zaix/models/db/download_status.dart';
import 'package:zaix/models/db/local_favorite.dart';
import 'package:zaix/models/db/novel_download_info.dart';
import 'package:zaix/models/db/novel_history.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ComicDownloadInfoAdapter());
    registerAdapter(ComicHistoryAdapter());
    registerAdapter(DownloadStatusAdapter());
    registerAdapter(LocalFavoriteAdapter());
    registerAdapter(NovelDownloadInfoAdapter());
    registerAdapter(NovelHistoryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ComicDownloadInfoAdapter());
    registerAdapter(ComicHistoryAdapter());
    registerAdapter(DownloadStatusAdapter());
    registerAdapter(LocalFavoriteAdapter());
    registerAdapter(NovelDownloadInfoAdapter());
    registerAdapter(NovelHistoryAdapter());
  }
}
